window.CLOSER_PROJECTS = {
  "lab": [
    {
      "id": "tabby",
      "num": "4070 RTX",
      "tone": "cyan",
      "who": "Tabby Tavern Stack",
      "blurb": "Single-GPU private inference lab. Published to Hugging Face.",
      "bullets": [
        "Containerized private LLM stack on NVIDIA RTX 4070 / WSL2: Docker Compose, CUDA, GPU passthrough.",
        "TabbyAPI EXL3, SillyTavern, Open WebUI, Ollama, SearXNG — flash attention, q8 KV cache, auth, SECURITY.md.",
        "Forced CUDA layer offload, VRAM pre-warm, PID-file lifecycle, multi-port failover (Ollama + LiteLLM proxy to cloud).",
        "Published: huggingface.co/jpanasuk/tabby-tavern-stack"
      ]
    },
    {
      "id": "grid",
      "num": "27×",
      "tone": "purple",
      "who": "Local Grid Suite",
      "blurb": "Operator telemetry. Constant test loops, not one lucky run.",
      "bullets": [
        "Model discovery, decode/prefill benches, GPU routing, SQLite logs, CLI reporting, PDF output.",
        "Checked-in sample: qwen3:8b at 1.39 tok/s → qwen-gpu:latest at 37.47 tok/s after routing/tuning (~27×).",
        "Warm stream suite on qwen3:8b ~76 tok/s (400-token runs). Methodology in local_grid_suite/benchmarks.",
        "github.com/jpanasuk-netizen/local_grid_suite"
      ]
    },
    {
      "id": "mcp",
      "num": "MCP",
      "tone": "orange",
      "who": "Dockroot-MCP",
      "blurb": "Agents see Docker/network. They do not get host-root.",
      "bullets": [
        "Published MCP image for bounded visibility into Docker services and network wiring.",
        "Agents get inspect/list surfaces without host-root access.",
        "Same production discipline as Fortune-100 Grid/HA: measure the boundary, then hand the agent the boundary — not the box."
      ]
    },
    {
      "id": "agents",
      "num": "Agents",
      "tone": "green",
      "who": "Multi-agent pipeline + OpenClaw",
      "blurb": "Systems → architect → validator over local inference.",
      "bullets": [
        "Systems agent to architect to validator: structured output, repair retries, collision checks, regression checks on local Ollama.",
        "Honest prototype: playable HTML dungeon generated by local agents — github.com/jpanasuk-netizen/multi-agent-dungeon-crawler",
        "OpenClaw WhatsApp production agents with 10+ skills (GitHub, browser, search, mail, local execution).",
        "Multi-provider routing with cloud failover so agents call one surface for local and hosted models."
      ]
    }
  ],
  "playbook": [
    {
      "id": "playbook",
      "num": "IPS",
      "tone": "gold",
      "who": "The Playbook",
      "blurb": "Documentation standards. Real-world performance. Customer coaching. The operating path left on the table.",
      "bullets": [
        "Three artifacts before anyone touched config: Environment Summary, Upgrade Roadmap, Phase / architecture review — plus the v10 Upgrade Overview that taught the room how to choose an upgrade type and how to test it.",
        "Performance loop left with the team: baseline, goal, bottleneck, eliminate, repeat. Thread statistics before folklore. Do not partition until a single partition is understood.",
        "Customer coaching is a deliverable: named skill-up, walked loads, whole stack plus GCS in one room, the team praised in writing, a QA twin of production so the parachute is not required twice.",
        "Engagements in the source files: Northwestern Mutual, Mercedes-Benz Financial, Waddell & Reed, Farmers Insurance. Public site carries the operating findings. Hostnames stay in the customer copy.",
        "Same loop now pointed at the RTX lab: measure, isolate, document, hand off the boundary."
      ]
    },
    {
      "id": "docs",
      "num": "IPS",
      "tone": "cyan",
      "who": "Documentation standards",
      "blurb": "The three artifacts every burning platform got before anyone touched config.",
      "bullets": [
        "Environment Summary: who owns the platform, what is actually running, what was changed, what is still on fire, and the Grid/HA recommendation with evidence.",
        "Upgrade Roadmap: current utilization (CPU, RAM, disk, database), supported shared filesystems, HA internals, in-place vs parallel vs clone, and the testing plan that makes go-live honest.",
        "Phase / architecture review: what the next product increment actually requires (cores, services, skills), what the current topology will not survive, and outstanding demos so the customer can see the path.",
        "v10 Upgrade Overview: PAM, edition value, upgrade-type selection, and the six-class test strategy (operability, same-data, security, performance, 3rd-party, HA/DR).",
        "Public site carries the operating standard. Hostnames, credentials, and raw capacity tables stay in the customer copy."
      ]
    },
    {
      "id": "perf",
      "num": "Tune",
      "tone": "orange",
      "who": "Performance methodology",
      "blurb": "Baseline. Goal. Bottleneck. Eliminate. Repeat. Thread statistics before folklore.",
      "bullets": [
        "Establish baseline. Set a goal. Find the bottleneck. Eliminate it. Repeat until the goal is met or the bottleneck cannot be moved.",
        "Do not add partitions until you understand a single partition. Multiple partitions are harder to diagnose and can make source, target, or system bottlenecks worse.",
        "Thread statistics in the session log first. Transformation ~100% busy → repartition point. Reader/writer ~100% busy → maybe the thread, maybe the system.",
        "Isolation tests when threads lie: filter FALSE before target; source-only mapping; write to flat file vs bulk loader. Change one thing between runs.",
        "Dos: cache in memory, spread I/O, round-robin a single file until it is the bottleneck. Don’ts: partition a constrained session, partition when %idle is already under ~5%.",
        "Knuth on the floor: premature optimization is the root of all evil. Big problems before small. Simple before complex."
      ]
    },
    {
      "id": "coach",
      "num": "Coach",
      "tone": "green",
      "who": "Customer coaching",
      "blurb": "Leave the runbook and the team. Loyalty is the team that can run it after you leave.",
      "bullets": [
        "Knowledge transfer is a deliverable, not a slide. MBFS: ALFA→ODS, ODS→flat file, ODS→warehouse walked with the team. Mercedes: TCS kept the tuning docs.",
        "Skill-up is named in the architecture review. Farmers: Developer tool + Advanced XML for Guidewire. Navy Federal: install, services, naming standards, go-live tests.",
        "Bring the whole stack into the room with Global Customer Support. MBFS recommendation when production would not dispatch: architecture, OS, database, Informatica — one room.",
        "Praise the team in writing. Farmers: ‘very knowledgeable… openness to new suggestions… explanation of why they chose their current architecture.’",
        "The closer leaves a QA twin of production, a Grid/HA TCO path, and a performance cheat sheet — so the customer does not need the parachute twice."
      ]
    }
  ],
  "legend": [
    {
      "id": "bny",
      "num": "$2.3M+",
      "tone": "",
      "who": "BNY Mellon",
      "blurb": "Grid/HA with senior VPs, support, and CEO Sohaib Abbasi.",
      "bullets": [
        "Worked with Senior VPs, Sales, Informatica CEO Sohaib Abbasi, Support, and additional resources on a new GRID/HA architecture for the BNY Mellon integration platform.",
        "New GRID/HA environment on IBM hardware.",
        "Strategic account win: sales, services, and support revenue streams of over $2.3 million and growing."
      ]
    },
    {
      "id": "dawn",
      "num": "8h → 1h",
      "tone": "orange",
      "who": "Dawn Foods",
      "blurb": "PowerExchange CDC on AS/400 remote journals. Featured on informatica.com.",
      "bullets": [
        "Integration Platform Lead (IPS Consultant).",
        "Mentored Dawn personnel on Informatica environment management: coding standards, security, migration, upgrades, maintenance, and folder setups.",
        "Implemented Informatica PowerExchange for AS/400 using remote journals.",
        "Reduced data-warehouse load times from over 8 hours to under 1 hour.",
        "Managed the Type 2 data-warehouse project and mentored reporting and integration staff on Type 2 warehouse and reporting best practices.",
        "Featured on informatica.com.",
        "Client: “Jeremy has been a pleasure and an asset to work with. His knowledge not only of the Informatica suite but also at the operating system level has been truly invaluable.”",
        "IPS sales: “He’s a rock star out at Dawn. The customer loves him and the sales team has been leaning on him hard.”"
      ]
    },
    {
      "id": "mf",
      "num": "20+ nodes",
      "tone": "",
      "who": "MF Global",
      "blurb": "World-first Informatica Grid/HA plus DR on RHEL GFS. India, UK, New York, Chicago.",
      "bullets": [
        "Worldwide Platform Lead for consultants and in-house development: IDQ, PowerCenter, PowerExchange, and B2B across India, the United Kingdom, New York, and Chicago.",
        "One of the first Informatica PowerCenter Grid/HA environments in the world with DR — RedHat GFS 1.0 on Linux, live switch from Windows/CIFS.",
        "Set, reviewed, and implemented architectural standards from Windows to Linux HA with Grid, including cluster file systems, NAS, NFS, Linux security, and multiple application servers.",
        "Managed code releases across four regions. Informatica installed and configured on 20+ nodes.",
        "Level 4 developer support. Primary contact for Informatica Global Customer Support.",
        "Created the disaster-recovery process for the entire Informatica platform (app servers, database servers, source/target staging) and participated in the U.S. DR test.",
        "Infrastructure staff: “It is the belief of the infrastructure staff that you have sent one of the best that Informatica has to offer in Jeremy.”"
      ]
    },
    {
      "id": "micron",
      "num": "7,000h",
      "tone": "gold",
      "who": "Micron",
      "blurb": "Teradata and Hadoop EDW. 2,080 → 7,000 hours. Consultant of the Year runner-up.",
      "bullets": [
        "Teradata and Hadoop EDW to unify data across disparate fabrication sites.",
        "Delivered a 7,000-hour resourcing plan (originally 2,080) covering PowerExchange, PowerCenter Grid/HA, Fast Clone, and Big Data Edition.",
        "On-time delivery with multiple extensions. Extensions and estimated extensions in the $2.2M–$3M range. Ongoing ELAs.",
        "Managed resourcing, budget, billing, and status in Financial Force. Drafted SOWs through critical software buys.",
        "Consultant of the Year runner-up (2016). Zero downtime on the program."
      ]
    },
    {
      "id": "kohls",
      "num": "$2M",
      "tone": "",
      "who": "Kohl’s",
      "blurb": "Grid/HA capacity and upgrade roadmap. AIX to commodity hardware.",
      "bullets": [
        "Roadmap for capacity planning and upgrade to Informatica version 9, including multiple HA and grid components.",
        "Switch from AIX to commodity hardware.",
        "Presented through multiple levels of the organization up to Senior VPs.",
        "$2 million software deal."
      ]
    },
    {
      "id": "mercedes",
      "num": "+200%",
      "tone": "orange",
      "who": "Mercedes-Benz",
      "blurb": "Parachute performance rescue on the longest-running workflows. Trained TCS on the path.",
      "bullets": [
        "Parachuted in to train the team on performance-tuning best practices.",
        "Developed new mappings and suggested new ways of extracting data with the Informatica toolset.",
        "200%+ performance improvement on the longest-running workflows.",
        "$500k deal. Tuning documentation adopted by the TCS team."
      ]
    },
    {
      "id": "toyota",
      "num": "$800k",
      "tone": "",
      "who": "Toyota",
      "blurb": "Engine Management product go-live. All consultants rated 5/5.",
      "bullets": [
        "Engine Management — complex implementation strategy and go-live.",
        "Worked with Regional Managers and Sales to scope, resource, and deliver a multi-product engagement: project management, technical resolution, and sales upsells.",
        "All consultants received 5/5 ratings.",
        "$300k in new professional services agreements plus $500k in new product licensing."
      ]
    },
    {
      "id": "smith",
      "num": "$600k",
      "tone": "",
      "who": "Smith & Nephew",
      "blurb": "FDA-validated Informatica platform. Licensing contention and platform risk resolved.",
      "bullets": [
        "Worked with senior project managers and architects to deploy an FDA-approved validated Informatica platform.",
        "Mitigated licensing and resource contention.",
        "Influenced best practices in an organization that was indifferent to application deployment.",
        "Estimated overall sizing and data growth. Helped Informatica Sales close a $600k licensing deal."
      ]
    },
    {
      "id": "navy",
      "num": "3,000h",
      "tone": "",
      "who": "Navy Federal",
      "blurb": "Informatica and BI V1 resourcing plan from architecture through go-live training.",
      "bullets": [
        "Helped develop and deliver a 3,000-hour resourcing plan for the Informatica platform and V1 release with Informatica’s Resource Management Office and NFCU HR.",
        "Hands-on PowerCenter platform installation: PowerCenter, Metadata Manager, Data Quality, DVO, PowerExchange CDC for DB2 on mainframe and AS/400, Web Services.",
        "Developed the “Informatica Technical Stack” testing strategy for go-live and business acceptance.",
        "Mentored and trained the NFCU team on installation, services configuration, best practices, development, and naming standards."
      ]
    },
    {
      "id": "westbend",
      "num": "−50%",
      "tone": "orange",
      "who": "West Bend Mutual",
      "blurb": "Real-time SOAP/XML runtime cut in half. Team enablement for Windows services.",
      "bullets": [
        "50% improvement for real-time SOAP-based XML sources and targets.",
        "Reduced agent quote turnaround time.",
        "Trained staff on performance-tuning best practices for Windows."
      ]
    },
    {
      "id": "cargill",
      "num": "CFO Award",
      "tone": "green",
      "who": "Cargill",
      "blurb": "2005 CFO Award — six awarded per year. Quarterly Award for Excellence, 2006.",
      "bullets": [
        "Integration Associate: designed integration software across multiple projects.",
        "24/7 support for data integration and data warehousing applications.",
        "Cargill CFO Award, 2005 — six awarded per year, the highest award for financial teams.",
        "Quarterly Award for Excellence, 2006, Demantra forecasting."
      ]
    },
    {
      "id": "jpmc",
      "num": "$10M+",
      "tone": "",
      "who": "JPMorgan Chase",
      "blurb": "Enterprise DW roadmaps and Center-of-Excellence evaluations presented to senior management.",
      "bullets": [
        "Enterprise GRID/HA data warehouse planning with Sales, Regional Managers, and IPS VPs.",
        "Created DW roadmaps, standards, Center-of-Excellence evaluations, and proofs of concept.",
        "Presentations to senior JPMC management.",
        "Worth over $10 million in ELA license and professional services revenue."
      ]
    },
    {
      "id": "harvard",
      "num": "v9",
      "tone": "cyan",
      "who": "Harvard",
      "blurb": "Version 9 upgrade. Off-load Solaris 8.1.1. Resource plan through post-production support.",
      "bullets": [
        "Developed Harvard’s strategy for upgrading to the Informatica Version 9 platform.",
        "Off-loaded the old Solaris 8.1.1 environment.",
        "Implemented Version 9 including resource planning through post-production support."
      ]
    },
    {
      "id": "pepsico",
      "num": "v9→v10",
      "tone": "purple",
      "who": "PepsiCo",
      "blurb": "Grid/HA and Data Integration Hub across NA/LATAM. v9→v10 with zero data loss.",
      "bullets": [
        "Informatica Specialist at TCS: Grid/HA and Data Integration Hub across NA/LATAM.",
        "Supported DIH, NA/Grid, and LATAM PowerCenter platforms; worked with data engineers to resolve issues across the platform.",
        "Led the v9→v10 upgrade, migrating workflows, connections, and domain configurations with zero data loss.",
        "Teradata warehouse → Big Data ecosystem — about 40% analytics lift.",
        "Day-to-day: users and groups, security, connections, POC installs, workflow migrations, follow-the-sun support with the offshore team."
      ]
    },
    {
      "id": "mobe",
      "num": "99.99%",
      "tone": "cyan",
      "who": "MOBE",
      "blurb": "Talend 8 mappings. GitLab CI/CD. Redshift and SQL Server. Jul 2023 – Aug 2024.",
      "bullets": [
        "Senior Software Developer, Minneapolis — July 2023 to August 2024.",
        "Simple, medium, and complex Talend 8 mappings using MOBE data-integration patterns.",
        "Production code migrations via GitLab CI/CD.",
        "Optimized SQL pipelines for Redshift and SQL Server while holding 99.99% system stability.",
        "Resolved long-running jobs, failed executions, and production bugs."
      ]
    },
    {
      "id": "ace",
      "num": "Big Data",
      "tone": "",
      "who": "Ace Hardware",
      "blurb": "Teradata warehouse to Big Data objects and runtimes. Business + QA deploy path.",
      "bullets": [
        "Supported Ace Hardware’s transition of the Teradata warehouse to a Big Data ecosystem.",
        "Informatica Big Data Engineering: convert PowerCenter workflows into Big Data objects and runtime environments.",
        "Worked with business users to obtain requirements for the conversion.",
        "Worked with business users and QA testers to fix and deploy code."
      ]
    },
    {
      "id": "ameriprise",
      "num": "24×7 EDG",
      "tone": "purple",
      "who": "Ameriprise",
      "blurb": "Enterprise Data Governance: IDQ, Enterprise Data Catalog, and Axon on financial systems.",
      "bullets": [
        "Enterprise Data Governance initiative at Ameriprise Financial.",
        "Connected financial systems to Informatica Data Quality, Enterprise Data Catalog, and Axon.",
        "Worked with business users to gather requirements and fix issues on the Informatica project.",
        "Maintained the platform 24×7: bug fixes, patches, and service restarts.",
        "Worked with Local Data Governance groups to define enhancements and roll them out on the EDG platform."
      ]
    },
    {
      "id": "prime",
      "num": "5/5",
      "tone": "green",
      "who": "Prime Therapeutics",
      "blurb": "Sr. Integration Engineer, 2007–2008. The quality quote that still travels.",
      "bullets": [
        "Sr. Integration Engineer, January 2007 – June 2008.",
        "Delivered assigned integration work at a grade-level that management said he exceeded.",
        "Client: “I trusted that Jeremy would deliver, with quality, on the project he was assigned. Jeremy has exceeded the expectations at someone of his grade level.”"
      ]
    },
    {
      "id": "farmers",
      "num": "Phase 2",
      "tone": "cyan",
      "who": "Farmers Insurance",
      "blurb": "Guidewire XML, 30+ repositories, NFS vs CFS. Phase 2 architecture review plus team coaching.",
      "bullets": [
        "Architecture review (Oct 2017) for Farmers Phase 2: consume advanced Guidewire XML on the Mercury platform.",
        "Recommended Model Repository Service and Data Integration Service in dev and production, plus cores/nodes for real-time web-service consumers.",
        "Flagged 30+ repositories and 30+ integration services as TCP/IP overhead that hangs domains and makes upgrades expensive.",
        "File-system coaching: NFS on NAS is Informatica’s least-recommended HA/performance path; Veritas CFS or GPFS with host-side striping is the Grid/HA baseline.",
        "Skill-up the team on Developer tool + Advanced XML. Outstanding demos: Proactive Monitoring / Operational Insight and Advanced XML on Farmers Guidewire XML.",
        "On the floor: the team was knowledgeable and open. They explained why they chose the current architecture and where it had to improve."
      ]
    },
    {
      "id": "mbfs",
      "num": "20–30%",
      "tone": "orange",
      "who": "Mercedes-Benz Financial",
      "blurb": "Environment summary plus the performance cheat sheet left with the team. Cache memory, not more hardware.",
      "bullets": [
        "PowerCenter Environment Recommendations (Jun 2017). Author and owner: Jeremy Panasuk.",
        "Peak ALFA→ODS loads sat at 100% CPU; DB2 loader path ~50%. Repository recommended off the shared DB host so purchased cores stay on Informatica.",
        "Raised RAM for sorters, aggregators, lookups, and joiners so large transformations stop spilling cache to disk — 20–30% decrease in job runtime.",
        "Knowledge transfer on ALFA→ODS, ODS→flat file, and ODS→data warehouse. POC recommended: PowerExchange for DB2 CDC/batch vs bulk load.",
        "File system: GFS2 lacks flock; DB persistence for split-brain costs performance. Recommended Veritas Cluster File System.",
        "Left the performance cheat sheet: baseline, goal, bottleneck, eliminate, repeat. Do not partition until a single partition is understood."
      ]
    },
    {
      "id": "nwm",
      "num": "P1",
      "tone": "green",
      "who": "Northwestern Mutual",
      "blurb": "Domain best-practice config, P1 DB2 start delay, Grid/HA TCO path, QA twin of production.",
      "bullets": [
        "PowerCenter Environment Recommendations (Apr 2017). PWX CDC and DB2 loads were inside resource limits; the work was configuration and operating path.",
        "Configured QA and production domains to best practices: ulimit open files to 64k, DB2 repo/domain settings, concurrent jobs to 500 on measured low utilization, Java heap, stale log cleanup on NFS.",
        "Resolved P1: workflows delayed connecting to DB2. Escalated with Informatica support. DB2 semaphore required when starting the DB2 client on Informatica.",
        "Reviewed Tidal scheduling and PowerCenter Proactive Monitoring. In-place vs dual-system upgrade, batch/CR consolidation, v10 features.",
        "TCO path: Grid/HA so batch and continuous-run live in one domain with Gold/Platinum SLA tiers. QA domain identical to production so troubleshooting does not take prod down."
      ]
    },
    {
      "id": "wr",
      "num": "v9→v10",
      "tone": "purple",
      "who": "Waddell & Reed",
      "blurb": "Upgrade roadmap v3: measured I/O wait, UNC is not HA, in-place vs parallel vs clone.",
      "bullets": [
        "Informatica Upgrade Roadmap v3 (Jun 2017) for a 2-node PowerCenter 9.1.0 grid plus 9.6.1 Data Quality on Windows.",
        "Measured the platform: round-robin dispatch left both nodes at 80–90% CPU in peak; RAM under-used while cache spilled to disk; disk wait 30 ms typical, month-end spikes above 90 ms.",
        "SQL Server disk wait spiked past 200 ms with RAM sitting idle — the bottleneck was I/O, not ‘need more ETL boxes.’",
        "UNC share as the shared filesystem: no simultaneous read, not a POSIX HA CFS. Session on Grid disabled; DB persistence tax. Recommendation: Linux + Veritas CFS or GPFS.",
        "Upgrade types taught: in-place vs parallel vs clone, with the testing taxonomy — operability, same-data, security, performance, 3rd-party, HA/DR — accelerated with Data Validation Option."
      ]
    },
    {
      "id": "fireworks",
      "num": "1996–04",
      "tone": "gold",
      "who": "Secret Key / Fireworks Forever",
      "blurb": "Class B fireworks shooter. Inventory manager. The floor that forged the loyalty line.",
      "bullets": [
        "Secret Key — Class B fireworks shooter, 1996–2004. Professional display work: load, wire, shoot, and tear down the show.",
        "Fireworks Forever — Inventory Manager & Sales Lead, 1996–2004.",
        "Managed $800K+ seasonal fireworks inventory with 6 consecutive years of profit growth.",
        "Purchasing, pricing, vendor negotiation, staffing, seasonal demand forecasting, and end-of-season reconciliation.",
        "Relationship-driven sales and on-the-floor customer engagement. Repeat business, not one-night receipts.",
        "100-hour peak weeks through July 4th and New Year — weekends and holidays included.",
        "Originated the operating line later formalized as the Informatica presentation: customer satisfaction is worthless; customer loyalty is priceless (Gitomer, Carnegie, Greene)."
      ]
    }
  ]
};
