window.CLOSER_PROJECTS = {
  "lab": [
    {
      "id": "tabby",
      "num": "4070 RTX",
      "tone": "cyan",
      "who": "Tabby Tavern Stack",
      "blurb": "Single-GPU private inference lab. Published to Hugging Face.",
      "bullets": [
        "Containerized private LLM stack on NVIDIA RTX 4070 / WSL2: Docker Compose, CUDA, GPU passthrough.",
        "TabbyAPI EXL3, SillyTavern, Open WebUI, Ollama, SearXNG — flash attention, q8 KV cache, auth, SECURITY.md.",
        "Forced CUDA layer offload, VRAM pre-warm, PID-file lifecycle, multi-port failover (Ollama + LiteLLM proxy to cloud).",
        "Published: huggingface.co/jpanasuk/tabby-tavern-stack"
      ]
    },
    {
      "id": "grid",
      "num": "27×",
      "tone": "purple",
      "who": "Local Grid Suite",
      "blurb": "Operator telemetry. Constant test loops, not one lucky run.",
      "bullets": [
        "Model discovery, decode/prefill benches, GPU routing, SQLite logs, CLI reporting, PDF output.",
        "Checked-in sample: qwen3:8b at 1.39 tok/s → qwen-gpu:latest at 37.47 tok/s after routing/tuning (~27×).",
        "Warm stream suite on qwen3:8b ~76 tok/s (400-token runs). Methodology in local_grid_suite/benchmarks.",
        "github.com/jpanasuk-netizen/local_grid_suite"
      ]
    },
    {
      "id": "mcp",
      "num": "MCP",
      "tone": "orange",
      "who": "Dockroot-MCP",
      "blurb": "Agents see Docker/network. They do not get host-root.",
      "bullets": [
        "Published MCP image for bounded visibility into Docker services and network wiring.",
        "Agents get inspect/list surfaces without host-root access.",
        "Same production discipline as Fortune-100 Grid/HA: measure the boundary, then hand the agent the boundary — not the box."
      ]
    },
    {
      "id": "agents",
      "num": "Agents",
      "tone": "green",
      "who": "Multi-agent pipeline + OpenClaw",
      "blurb": "Systems → architect → validator over local inference.",
      "bullets": [
        "Systems agent to architect to validator: structured output, repair retries, collision checks, regression checks on local Ollama.",
        "Honest prototype: playable HTML dungeon generated by local agents — github.com/jpanasuk-netizen/multi-agent-dungeon-crawler",
        "OpenClaw WhatsApp production agents with 10+ skills (GitHub, browser, search, mail, local execution).",
        "Multi-provider routing with cloud failover so agents call one surface for local and hosted models."
      ]
    }
  ],
  "legend": [
    {
      "id": "bny",
      "num": "$2.3M+",
      "tone": "",
      "who": "BNY Mellon",
      "blurb": "Grid/HA with senior VPs, support, and CEO Sohaib Abbasi.",
      "bullets": [
        "Worked with Senior VPs, Sales, Informatica CEO Sohaib Abbasi, Support, and additional resources on a new GRID/HA architecture for the BNY Mellon integration platform.",
        "New GRID/HA environment on IBM hardware.",
        "Strategic account win: sales, services, and support revenue streams of over $2.3 million and growing."
      ]
    },
    {
      "id": "dawn",
      "num": "8h → 1h",
      "tone": "orange",
      "who": "Dawn Foods",
      "blurb": "PowerExchange CDC on AS/400 remote journals. Featured on informatica.com.",
      "bullets": [
        "Integration Platform Lead (IPS Consultant).",
        "Mentored Dawn personnel on Informatica environment management: coding standards, security, migration, upgrades, maintenance, and folder setups.",
        "Implemented Informatica PowerExchange for AS/400 using remote journals.",
        "Reduced data-warehouse load times from over 8 hours to under 1 hour.",
        "Managed the Type 2 data-warehouse project and mentored reporting and integration staff on Type 2 warehouse and reporting best practices.",
        "Featured on informatica.com.",
        "Client: “Jeremy has been a pleasure and an asset to work with. His knowledge not only of the Informatica suite but also at the operating system level has been truly invaluable.”",
        "IPS sales: “He’s a rock star out at Dawn. The customer loves him and the sales team has been leaning on him hard.”"
      ]
    },
    {
      "id": "mf",
      "num": "20+ nodes",
      "tone": "",
      "who": "MF Global",
      "blurb": "World-first Informatica Grid/HA plus DR on RHEL GFS. India, UK, New York, Chicago.",
      "bullets": [
        "Worldwide Platform Lead for consultants and in-house development: IDQ, PowerCenter, PowerExchange, and B2B across India, the United Kingdom, New York, and Chicago.",
        "One of the first Informatica PowerCenter Grid/HA environments in the world with DR — RedHat GFS 1.0 on Linux, live switch from Windows/CIFS.",
        "Set, reviewed, and implemented architectural standards from Windows to Linux HA with Grid, including cluster file systems, NAS, NFS, Linux security, and multiple application servers.",
        "Managed code releases across four regions. Informatica installed and configured on 20+ nodes.",
        "Level 4 developer support. Primary contact for Informatica Global Customer Support.",
        "Created the disaster-recovery process for the entire Informatica platform (app servers, database servers, source/target staging) and participated in the U.S. DR test.",
        "Infrastructure staff: “It is the belief of the infrastructure staff that you have sent one of the best that Informatica has to offer in Jeremy.”"
      ]
    },
    {
      "id": "micron",
      "num": "7,000h",
      "tone": "gold",
      "who": "Micron",
      "blurb": "Teradata and Hadoop EDW. 2,080 → 7,000 hours. Consultant of the Year runner-up.",
      "bullets": [
        "Teradata and Hadoop EDW to unify data across disparate fabrication sites.",
        "Delivered a 7,000-hour resourcing plan (originally 2,080) covering PowerExchange, PowerCenter Grid/HA, Fast Clone, and Big Data Edition.",
        "On-time delivery with multiple extensions. Extensions and estimated extensions in the $2.2M–$3M range. Ongoing ELAs.",
        "Managed resourcing, budget, billing, and status in Financial Force. Drafted SOWs through critical software buys.",
        "Consultant of the Year runner-up (2016). Zero downtime on the program."
      ]
    },
    {
      "id": "kohls",
      "num": "$2M",
      "tone": "",
      "who": "Kohl’s",
      "blurb": "Grid/HA capacity and upgrade roadmap. AIX to commodity hardware.",
      "bullets": [
        "Roadmap for capacity planning and upgrade to Informatica version 9, including multiple HA and grid components.",
        "Switch from AIX to commodity hardware.",
        "Presented through multiple levels of the organization up to Senior VPs.",
        "$2 million software deal."
      ]
    },
    {
      "id": "mercedes",
      "num": "+200%",
      "tone": "orange",
      "who": "Mercedes-Benz",
      "blurb": "Parachute performance rescue on the longest-running workflows. Trained TCS on the path.",
      "bullets": [
        "Parachuted in to train the team on performance-tuning best practices.",
        "Developed new mappings and suggested new ways of extracting data with the Informatica toolset.",
        "200%+ performance improvement on the longest-running workflows.",
        "$500k deal. Tuning documentation adopted by the TCS team."
      ]
    },
    {
      "id": "toyota",
      "num": "$800k",
      "tone": "",
      "who": "Toyota",
      "blurb": "Engine Management product go-live. All consultants rated 5/5.",
      "bullets": [
        "Engine Management — complex implementation strategy and go-live.",
        "Worked with Regional Managers and Sales to scope, resource, and deliver a multi-product engagement: project management, technical resolution, and sales upsells.",
        "All consultants received 5/5 ratings.",
        "$300k in new professional services agreements plus $500k in new product licensing."
      ]
    },
    {
      "id": "smith",
      "num": "$600k",
      "tone": "",
      "who": "Smith & Nephew",
      "blurb": "FDA-validated Informatica platform. Licensing contention and platform risk resolved.",
      "bullets": [
        "Worked with senior project managers and architects to deploy an FDA-approved validated Informatica platform.",
        "Mitigated licensing and resource contention.",
        "Influenced best practices in an organization that was indifferent to application deployment.",
        "Estimated overall sizing and data growth. Helped Informatica Sales close a $600k licensing deal."
      ]
    },
    {
      "id": "navy",
      "num": "3,000h",
      "tone": "",
      "who": "Navy Federal",
      "blurb": "Informatica and BI V1 resourcing plan from architecture through go-live training.",
      "bullets": [
        "Helped develop and deliver a 3,000-hour resourcing plan for the Informatica platform and V1 release with Informatica’s Resource Management Office and NFCU HR.",
        "Hands-on PowerCenter platform installation: PowerCenter, Metadata Manager, Data Quality, DVO, PowerExchange CDC for DB2 on mainframe and AS/400, Web Services.",
        "Developed the “Informatica Technical Stack” testing strategy for go-live and business acceptance.",
        "Mentored and trained the NFCU team on installation, services configuration, best practices, development, and naming standards."
      ]
    },
    {
      "id": "westbend",
      "num": "−50%",
      "tone": "orange",
      "who": "West Bend Mutual",
      "blurb": "Real-time SOAP/XML runtime cut in half. Team enablement for Windows services.",
      "bullets": [
        "50% improvement for real-time SOAP-based XML sources and targets.",
        "Reduced agent quote turnaround time.",
        "Trained staff on performance-tuning best practices for Windows."
      ]
    },
    {
      "id": "cargill",
      "num": "CFO Award",
      "tone": "green",
      "who": "Cargill",
      "blurb": "2005 CFO Award — six awarded per year. Quarterly Award for Excellence, 2006.",
      "bullets": [
        "Integration Associate: designed integration software across multiple projects.",
        "24/7 support for data integration and data warehousing applications.",
        "Cargill CFO Award, 2005 — six awarded per year, the highest award for financial teams.",
        "Quarterly Award for Excellence, 2006, Demantra forecasting."
      ]
    },
    {
      "id": "jpmc",
      "num": "$10M+",
      "tone": "",
      "who": "JPMorgan Chase",
      "blurb": "Enterprise DW roadmaps and Center-of-Excellence evaluations presented to senior management.",
      "bullets": [
        "Enterprise GRID/HA data warehouse planning with Sales, Regional Managers, and IPS VPs.",
        "Created DW roadmaps, standards, Center-of-Excellence evaluations, and proofs of concept.",
        "Presentations to senior JPMC management.",
        "Worth over $10 million in ELA license and professional services revenue."
      ]
    },
    {
      "id": "harvard",
      "num": "v9",
      "tone": "cyan",
      "who": "Harvard",
      "blurb": "Version 9 upgrade. Off-load Solaris 8.1.1. Resource plan through post-production support.",
      "bullets": [
        "Developed Harvard’s strategy for upgrading to the Informatica Version 9 platform.",
        "Off-loaded the old Solaris 8.1.1 environment.",
        "Implemented Version 9 including resource planning through post-production support."
      ]
    },
    {
      "id": "pepsico",
      "num": "v9→v10",
      "tone": "purple",
      "who": "PepsiCo",
      "blurb": "Grid/HA and Data Integration Hub across NA/LATAM. v9→v10 with zero data loss.",
      "bullets": [
        "Informatica Specialist at TCS: Grid/HA and Data Integration Hub across NA/LATAM.",
        "Supported DIH, NA/Grid, and LATAM PowerCenter platforms; worked with data engineers to resolve issues across the platform.",
        "Led the v9→v10 upgrade, migrating workflows, connections, and domain configurations with zero data loss.",
        "Teradata warehouse → Big Data ecosystem — about 40% analytics lift.",
        "Day-to-day: users and groups, security, connections, POC installs, workflow migrations, follow-the-sun support with the offshore team."
      ]
    },
    {
      "id": "mobe",
      "num": "99.99%",
      "tone": "cyan",
      "who": "MOBE",
      "blurb": "Talend 8 mappings. GitLab CI/CD. Redshift and SQL Server. Jul 2023 – Aug 2024.",
      "bullets": [
        "Senior Software Developer, Minneapolis — July 2023 to August 2024.",
        "Simple, medium, and complex Talend 8 mappings using MOBE data-integration patterns.",
        "Production code migrations via GitLab CI/CD.",
        "Optimized SQL pipelines for Redshift and SQL Server while holding 99.99% system stability.",
        "Resolved long-running jobs, failed executions, and production bugs."
      ]
    },
    {
      "id": "ace",
      "num": "Big Data",
      "tone": "",
      "who": "Ace Hardware",
      "blurb": "Teradata warehouse to Big Data objects and runtimes. Business + QA deploy path.",
      "bullets": [
        "Supported Ace Hardware’s transition of the Teradata warehouse to a Big Data ecosystem.",
        "Informatica Big Data Engineering: convert PowerCenter workflows into Big Data objects and runtime environments.",
        "Worked with business users to obtain requirements for the conversion.",
        "Worked with business users and QA testers to fix and deploy code."
      ]
    },
    {
      "id": "ameriprise",
      "num": "24×7 EDG",
      "tone": "purple",
      "who": "Ameriprise",
      "blurb": "Enterprise Data Governance: IDQ, Enterprise Data Catalog, and Axon on financial systems.",
      "bullets": [
        "Enterprise Data Governance initiative at Ameriprise Financial.",
        "Connected financial systems to Informatica Data Quality, Enterprise Data Catalog, and Axon.",
        "Worked with business users to gather requirements and fix issues on the Informatica project.",
        "Maintained the platform 24×7: bug fixes, patches, and service restarts.",
        "Worked with Local Data Governance groups to define enhancements and roll them out on the EDG platform."
      ]
    },
    {
      "id": "prime",
      "num": "5/5",
      "tone": "green",
      "who": "Prime Therapeutics",
      "blurb": "Sr. Integration Engineer, 2007–2008. The quality quote that still travels.",
      "bullets": [
        "Sr. Integration Engineer, January 2007 – June 2008.",
        "Delivered assigned integration work at a grade-level that management said he exceeded.",
        "Client: “I trusted that Jeremy would deliver, with quality, on the project he was assigned. Jeremy has exceeded the expectations at someone of his grade level.”"
      ]
    },
    {
      "id": "fireworks",
      "num": "1996–04",
      "tone": "gold",
      "who": "Secret Key / Fireworks Forever",
      "blurb": "Class B fireworks shooter. Inventory manager. The floor that forged the loyalty line.",
      "bullets": [
        "Secret Key — Class B fireworks shooter, 1996–2004. Professional display work: load, wire, shoot, and tear down the show.",
        "Fireworks Forever — Inventory Manager & Sales Lead, 1996–2004.",
        "Managed $800K+ seasonal fireworks inventory with 6 consecutive years of profit growth.",
        "Purchasing, pricing, vendor negotiation, staffing, seasonal demand forecasting, and end-of-season reconciliation.",
        "Relationship-driven sales and on-the-floor customer engagement. Repeat business, not one-night receipts.",
        "100-hour peak weeks through July 4th and New Year — weekends and holidays included.",
        "Originated the operating line later formalized as the Informatica presentation: customer satisfaction is worthless; customer loyalty is priceless (Gitomer, Carnegie, Greene)."
      ]
    }
  ]
};
